name: Идея
description: Идея для стикера
labels: ["идея"]
body:
  - type: markdown
    attributes:
      value: |
        Данная форма предназначена для добавление идеи стикеров для группы "IT встречи Паттайя".
        Выбираться идеи будут путем голосования с помощью реакции "👍" на идеи, и субъективному мнению админов группы)))
        
        **Внимание, пока что рассматриваются идеи только для статических стикеров.**
        
        **Дедлайн 12 августа**
  - type: textarea
    id: idea
    attributes:
      label: Идея
      description: Опишите идею для стикеров (идея ровно на 1 стикер)
      placeholder: Стикер не трогайте лодки с фотографией лодки
    validations:
      required: true
  - type: textarea
    id: photos
    attributes: 
      label: Фотографии
      description: Прикрепите фотографии для стикера если имеются сразу (можно будет прикрепить по мере осбуждения)
  - type: input
    id: emoji
    attributes:
      label: Смайлик
      description: Укажите смайлик для стикера (можно указать несколько)
      placeholder: 💩
    validations:
      required: true
  - type: textarea
    id: permisions
    attributes: 
      label: Разрешение на исползования фотографии 
      description: Добавьте людей которые на прикрепленной фотографии (тех кого знаете)
      placeholder: Душный админ
  - type: dropdown
    id: relevence
    attributes:
      label: Стикер относится к
      multiple: true
      options:
        - Встречам на пляже у Цетуса
        - Общению в чате "IT встречи Паттайя"
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Чеклист
      options:
        - label: Все люди на фотографиях дали согласие на их использование 
        - label: Стикер не содержит ничего нарушаюшие законы Таиланда и правила группы
          required: true
